# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"
unbind v
bind v split-window -v -c '#{pane_current_path}'  # Split panes vertically
unbind h
bind h split-window -h -c '#{pane_current_path}'  # Split panes horizontally
unbind c
bind c new-window -c '#{pane_current_path}'  # Create a new window
unbind S
bind S new-session
unbind w
bind w command-prompt "rename-window %%"
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix
set -g mouse on
set -g base-index 1
# set -g status-bg blue
# use ctrl-b + c instead of ctrl-b + [ to enter the copy mode
bind y copy-mode
# use v instead of Space to begin selection, like in vim
bind -T copy-mode-vi v send -X begin-selection
# use y instead of Enter to copy selection, like in vim
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
# Use vi keybindings in copy mode
setw -g mode-keys vi
# Address vim mode switching delay
set -s escape-time 10
set-option -g status-position top
# Fix proper colours
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"

set-option -g default-shell /usr/bin/fish
set-option -g default-command /usr/bin/fish
